### ISSUE TITLE
Can it works on Mac OS?

### ISSUE THREAD

**Issue by glight2000** [PySimpleGUI/psgtray#2]
When run the sample code on mac ox 11.6.
I got a error:`AttributeError: 'Icon' object has no attribute '_status_item'`

**Comment by PySimpleGUI** [comment]
Can you post the entire error message?

**Comment by glight2000** [comment]
Sure,
Error stack here:
```
/Users/username/anaconda3/envs/envname/bin/python /Users/username/Documents/Projects/Geek/envname/psg_tray.py
* Error performing wm_overrideredirect while hiding the hidden master root* expected boolean value but got ""
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/username/anaconda3/envs/envname/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/username/anaconda3/envs/envname/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/username/anaconda3/envs/envname/lib/python3.9/site-packages/psgtray/psgtray.py", line 183, in _pystray_thread
    self.tray_icon.menu = pystray.Menu(*self.menu_items)
  File "/Users/username/anaconda3/envs/envname/lib/python3.9/site-packages/pystray/_base.py", line 141, in menu
    self.update_menu()
  File "/Users/username/anaconda3/envs/envname/lib/python3.9/site-packages/pystray/_base.py", line 216, in update_menu
    self._update_menu()
  File "/Users/username/anaconda3/envs/envname/lib/python3.9/site-packages/pystray/_darwin.py", line 81, in _update_menu
    self._status_item.setMenu_(None)
AttributeError: 'Icon' object has no attribute '_status_item'

Process finished with exit code 1
```
