### ISSUE TITLE
tray_icon.notify NotImplementedError in Linux/X11 Py3.11

### ISSUE THREAD

**Issue by MeganerdDev** [PySimpleGUI/psgtray#9]
OS: Devuan (Debian 12 Bookworm)
Userland: X11
Python version: 3.11.1
Virtual environment: Yes(Poetry), but also seen on the system too

stdout:
```bash
$ python3.11 sgtraytest.py 
Traceback (most recent call last):
  File "/home/meganerd/Documents/GITLAB/atsu/sgtraytest.py", line 78, in <module>
    main()
  File "/home/meganerd/Documents/GITLAB/atsu/sgtraytest.py", line 37, in main
    tray.show_message('System Tray', 'System Tray Icon Started!')
  File "/home/meganerd/.cache/pypoetry/virtualenvs/atsu-6OHC88g4-py3.11/lib/python3.11/site-packages/psgtray/psgtray.py", line 127, in show_message
    self.tray_icon.notify(title=str(title) if title is not None else '', message=str(message) if message is not None else '')
  File "/home/meganerd/.cache/pypoetry/virtualenvs/atsu-6OHC88g4-py3.11/lib/python3.11/site-packages/pystray/_base.py", line 272, in notify
    self._notify(message, title)
  File "/home/meganerd/.cache/pypoetry/virtualenvs/atsu-6OHC88g4-py3.11/lib/python3.11/site-packages/pystray/_base.py", line 398, in _notify
    raise NotImplementedError()
NotImplementedError
```

**Comment by MeganerdDev** [comment]
tkinter version: 8.6.13
PySimpleGUI version: 4.60.5
